import { useState, useEffect, useRef, useCallback, useMemo } from "react";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from "recharts";

const C={bg:"#000",card:"#0a0a0a",card2:"#111",elevated:"#161616",border:"#1f1f1f",borderL:"#2c2c2c",
  or:"#ff6a00",orL:"#ff8533",orD:"rgba(255,106,0,0.10)",
  gn:"#00c853",gnD:"rgba(0,200,83,0.10)",rd:"#ff3b3b",rdD:"rgba(255,59,59,0.08)",
  bl:"#2196f3",blD:"rgba(33,150,243,0.10)",gd:"#ffab00",gdD:"rgba(255,171,0,0.10)",
  w:"#fff",t1:"#f0f0f0",t2:"#c0c0c0",t3:"#808080",t4:"#555"};
const PC=["#ff6a00","#00c853","#2196f3","#ff3b3b","#ffab00","#b388ff","#ff8533","#00e5ff","#ff6090","#76ff03","#ffd740","#ea80fc"];
const CATS=[
  {n:"Rent/Housing",t:"personal",i:"🏠"},{n:"Food/Groceries",t:"personal",i:"🛒"},{n:"Gas/Transport",t:"personal",i:"⛽"},
  {n:"Subscriptions",t:"personal",i:"📱"},{n:"Entertainment",t:"personal",i:"🎬"},{n:"Health",t:"personal",i:"💊"},
  {n:"Clothing",t:"personal",i:"👕"},{n:"Savings Transfer",t:"personal",i:"🏦"},{n:"Giving/Tithe",t:"personal",i:"💛"},
  {n:"Software/Tools",t:"business",i:"💻"},{n:"Advertising",t:"business",i:"📢"},{n:"Equipment/Gear",t:"business",i:"📷"},
  {n:"Business Travel",t:"business",i:"✈️"},{n:"Contractors",t:"business",i:"🤝"},{n:"Office/Supplies",t:"business",i:"📎"},
  {n:"Insurance",t:"business",i:"🛡️"},{n:"Taxes",t:"business",i:"📋"},{n:"Education",t:"business",i:"📚"},
];
const INIT={income:{sources:[]},expenses:[],savings:{accounts:[],transactions:[]},writeOffs:[],goals:[]};

const BIB=[
  {t:"Proverbs 21:5 — Plan With Purpose",v:"\"The thoughts of the diligent tend only to plenteousness; but of every one that is hasty only to want.\" — Proverbs 21:5 KJV",h:"God rewards the disciplined planner, not the hustler who wings it.",b:"This is a direct command to budget. The Hebrew word for diligent means sharp and decisive. When you plan every dollar before the month starts, you're obeying this verse. Hasty speculation, get-rich-quick schemes, and unplanned spending all lead to want. Slow, intentional building leads to plenteousness.\n\nApply it: Before every month, assign every dollar of expected income to a category. That act of planning is an act of faithfulness."},
  {t:"Proverbs 22:7 — Debt Is Slavery",v:"\"The rich ruleth over the poor, and the borrower is servant to the lender.\" — Proverbs 22:7 KJV",h:"Every debt payment is freedom you're handing to someone else. God designed you to be free.",b:"Solomon didn't use the word servant lightly. In ancient Israel debt slavery was real. Today it looks different but the principle is identical. When you owe a car payment or credit card balance, a portion of your future labor already belongs to someone else.\n\nThis doesn't mean all leverage is sinful. But debt should make you uncomfortable. It should be temporary, strategic, and attacked with urgency.\n\nApply it: List every debt by interest rate. Pay minimums on all, throw every extra dollar at the highest rate first. That's walking toward the freedom God designed for you."},
  {t:"Malachi 3:10 — The Tithe Test",v:"\"Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the Lord of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it.\" — Malachi 3:10 KJV",h:"This is the only place in scripture where God says \"prove me\" — test me. He's inviting you to try Him.",b:"The tithe is 10% given to your local church. It's the baseline of biblical generosity. Offerings go above and beyond.\n\nTithing isn't about God needing your money. He owns everything. It's about realigning your heart. When you give first, before bills, before buying anything, you're declaring God is your source and security, not your paycheck.\n\nR.G. LeTourneau, Truett Cathy, David Green — the wealthiest believers in history will tell you their breakthrough started when they got serious about tithing.\n\nApply it: Set up automatic giving. 10% off the top before anything else. Budget the remaining 90%. Watch God stretch it."},
  {t:"Proverbs 13:11 — Little by Little",v:"\"Wealth gotten by vanity shall be diminished: but he that gathereth by labour shall increase.\" — Proverbs 13:11 KJV",h:"Compound interest was a biblical principle 3,000 years before savings accounts existed.",b:"The Hebrew implies gathering grain handful by handful, harvest after harvest. $200/month into an index fund for 30 years at 10% average return becomes over $450,000. Not from one big move. From showing up every single month.\n\nApply it: Automate a savings transfer every payday. Even $25/week is $2,600/year. The habit matters more than the amount."},
  {t:"Luke 14:28 — Jesus Said Budget",v:"\"For which of you, intending to build a tower, sitteth not down first, and counteth the cost, whether he have sufficient to finish it?\" — Luke 14:28 KJV",h:"Jesus Himself said the wise person sits down and runs the numbers before starting anything.",b:"This destroys the idea that faith means being reckless with money. Faith is trusting God while being a faithful steward, which includes doing the math.\n\nApply it: Before any purchase over $100, wait 24 hours. Ask: do I need this, can I afford this, does this align with what God has called me to right now?"},
  {t:"Matthew 25:14-30 — Parable of the Talents",v:"\"For unto every one that hath shall be given, and he shall have abundance: but from him that hath not shall be taken away even that which he hath.\" — Matthew 25:29 KJV",h:"The servant who buried his money out of fear was called wicked and lazy. God expects a return on what He gives you.",b:"Two servants invested and multiplied. One buried his out of fear. The master's response was brutal. Fear of risk, fear of failure, fear of loss — Jesus condemned that as unfaithfulness. Letting money sit idle when it could be growing is not wise stewardship. It's disobedience disguised as caution.\n\nApply it: Don't let money sit in checking earning nothing. Open a HYSA for emergencies and invest everything beyond that. Put your talents to work."},
  {t:"Proverbs 27:23-24 — Know Your Numbers",v:"\"Be thou diligent to know the state of thy flocks, and look well to thy herds. For riches are not for ever